### ISSUE TITLE
Failed to load on IE11

### ISSUE THREAD

**Issue by eHyve** [sebastienlevert/spfx-angular-boilerplate#11]
Hi Sebastien,
Thanks a lot for the great article and package. I have tried for days now to setup the solution but still facing an issue with IE. When inserting the webpart, the following error message occurs. This is OK on Chrome however. I've tried several times to clean my npm cache, resinstall packages, no success... Thanks for any help.

***ERROR MESSAGE:
***Failed to load component "21e6e37b-9cb5-40d7-83d3-f09199970405" (BasicAngularWebPart).
Original error: ***Failed to load entry point from component "21e6e37b-9cb5-40d7-83d3-f09199970405" (BasicAngularWebPart).
Original error: Error loading https://component-id.invalid/21e6e37b-9cb5-40d7-83d3-f09199970405_0.0.1
	Object doesn't support property or method 'assign'

***CALLSTACK:
Error: ***Failed to load component "21e6e37b-9cb5-40d7-83d3-f09199970405" (BasicAngularWebPart).
Original error: ***Failed to load entry point from component "21e6e37b-9cb5-40d7-83d3-f09199970405" (BasicAngularWebPart).
Original error: Error loading https://component-id.invalid/21e6e37b-9cb5-40d7-83d3-f09199970405_0.0.1
	Object doesn't support property or method 'assign'
   at Anonymous function (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:16234:9)
   at e.prototype.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:17761)
   at r.prototype.run (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:12992)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:22666)
   at e.prototype.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:18418)
   at r.prototype.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:13692)
   at o (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:10761)
   at invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.12/zone.min.js:1:19560)

**Comment by mananchoksi007** [comment]
Did any one able to resolve this issue? Still its not working in IE

**Comment by sebastienlevert** [comment]
Was fixed in the latest Master merge! Please update your code to the latest version and should work!
